import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,randomBytes} from 'node:crypto';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:3000';
const admin={'oai-authenticated-user-id':'local-test-admin','oai-authenticated-user-email':'anotida174@icloud.com'};
async function request(path,{method='GET',body,headers={}}={}){const r=await fetch(base+path,{method,headers:{...(body instanceof FormData?{}:{'Content-Type':'application/json'}),...headers},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});let data;try{data=await r.json()}catch{}return{status:r.status,data};}
const proof=()=>{const f=new FormData();f.set('proof',new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aY4cAAAAASUVORK5CYII=','base64')],{type:'image/png'}),'sample-pop.png');return f;};
test('durable booking checkout, ownership, PoP review, payment balance and cancellation',async()=>{
 assert.equal((await request('/api/admin/bookings')).status,401);
 assert.equal((await request('/api/admin/bookings',{headers:{...admin,'oai-authenticated-user-email':'visitor@example.com'}})).status,403);
 const config=(await request('/api/config')).data;assert.equal(config.bank.demo,true);let date,slots;
 for(let day=0;day<60;day++){const d=new Date(config.startDate+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+day);date=d.toISOString().slice(0,10);slots=(await request(`/api/availability?service=micro&date=${date}`)).data.slots;if(slots?.length)break;}assert.ok(slots.length);
 const token=randomBytes(32).toString('hex');const payload={serviceId:'micro',date,time:slots[0].time,name:'Checkout test',email:randomUUID()+'@example.com',phone:'0660000000',placement:'forearm',idea:'A small botanical flower',consent:true,idempotencyKey:randomUUID(),accessToken:token};
 const competingToken=randomBytes(32).toString('hex');const competingPayload={...payload,email:randomUUID()+'@example.com',idempotencyKey:randomUUID(),accessToken:competingToken};const [a,b]=await Promise.all([request('/api/bookings',{method:'POST',body:payload}),request('/api/bookings',{method:'POST',body:competingPayload})]);assert.deepEqual([a.status,b.status].sort(),[201,409]);const created=a.status===201?a:b;const customerHeaders={Authorization:'Bearer '+(a.status===201?token:competingToken)};
 // Use the successful request's access token even if the competing write won.
 const winnerPayload=a.status===201?payload:competingPayload;
 const id=created.data.booking.id;assert.equal(created.data.booking.deposit,400);assert.equal((await request(`/api/bookings/${id}`)).status,403);assert.equal((await request(`/api/bookings/${id}`,{headers:customerHeaders})).status,200);
 assert.equal((await request('/api/bookings',{method:'POST',body:winnerPayload})).data.booking.id,id);
 const other=await request('/api/bookings',{method:'POST',body:{...payload,idempotencyKey:randomUUID(),accessToken:randomBytes(32).toString('hex')}});assert.equal(other.status,409);
 const bad=new FormData();bad.set('proof',new Blob(['<script>alert(1)</script>'],{type:'image/png'}),'bad.png');assert.equal((await request(`/api/bookings/${id}/proofs`,{method:'POST',body:bad,headers:customerHeaders})).status,400);
 const upload=await request(`/api/bookings/${id}/proofs`,{method:'POST',body:proof(),headers:customerHeaders});assert.equal(upload.status,201);assert.equal(upload.data.booking.status,'payment_review');const proofId=upload.data.proof.id;
 assert.equal((await request(`/api/admin/proofs/${proofId}/file`)).status,401);
 const file=await fetch(base+`/api/admin/proofs/${proofId}/file`,{headers:admin});assert.equal(file.status,200);assert.equal(file.headers.get('content-type'),'image/png');
 const verified=await request(`/api/admin/proofs/${proofId}`,{method:'PATCH',headers:admin,body:{decision:'approve',amount:400}});assert.equal(verified.status,200);assert.equal(verified.data.booking.status,'confirmed');assert.equal(verified.data.booking.paid_amount,400);
 assert.equal((await request(`/api/admin/proofs/${proofId}`,{method:'PATCH',headers:admin,body:{decision:'approve',amount:400}})).status,409);
 assert.equal((await request(`/api/admin/bookings/${id}`,{method:'PATCH',headers:admin,body:{action:'completed'}})).status,400);
 const balance=await request(`/api/admin/bookings/${id}`,{method:'PATCH',headers:admin,body:{action:'record_payment',amount:400,note:'Sample balance at studio'}});assert.equal(balance.data.booking.paid_amount,800);assert.equal(balance.data.booking.payment_status,'paid');
 assert.equal((await request(`/api/admin/bookings/${id}`,{method:'PATCH',headers:admin,body:{action:'completed'}})).data.booking.status,'completed');
 const available=(await request(`/api/availability?service=micro&date=${date}`)).data.slots;assert.ok(available.length);const secondToken=randomBytes(32).toString('hex');const second=await request('/api/bookings',{method:'POST',body:{...payload,time:available.at(-1).time,email:randomUUID()+'@example.com',idempotencyKey:randomUUID(),accessToken:secondToken}});assert.equal(second.status,201);const secondId=second.data.booking.id;const secondHeaders={Authorization:'Bearer '+secondToken};const up2=await request(`/api/bookings/${secondId}/proofs`,{method:'POST',headers:secondHeaders,body:proof()});const reject=await request(`/api/admin/proofs/${up2.data.proof.id}`,{method:'PATCH',headers:admin,body:{decision:'reject',reason:'Please include the payment reference.'}});assert.equal(reject.data.booking.status,'pending_payment');assert.equal((await request(`/api/bookings/${secondId}/proofs`,{method:'POST',headers:secondHeaders,body:proof()})).status,201);
 const cancel=await request(`/api/admin/bookings/${secondId}`,{method:'PATCH',headers:admin,body:{action:'cancelled'}});assert.equal(cancel.data.booking.status,'cancelled');assert.equal((await request(`/api/bookings/${secondId}/proofs`,{method:'POST',headers:secondHeaders,body:proof()})).status,409);const released=(await request(`/api/availability?service=micro&date=${date}`)).data.slots;assert.ok(released.some(s=>s.time===available.at(-1).time));
});
