import {SERVICES,SCHEDULE,BANK,slotsForDate} from './config.js';
import {db,prepare,first,all,publicBooking} from './db.js';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new HttpError(status,message)};
const uuid=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const hash=async s=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(b=>b.toString(16).padStart(2,'0')).join('');
function text(value,label,max=100,optional=false){if(typeof value!=='string'||(!optional&&!value.trim())||value.length>max)fail(400,`Please enter a valid ${label}.`);return value.trim();}
async function body(request){try{return await request.json()}catch{fail(400,'The request could not be read. Please try again.')}}
function admin(request,env){const email=request.headers.get('oai-authenticated-user-email')?.toLowerCase();const id=request.headers.get('oai-authenticated-user-id');if(!email||!id)fail(401,'Sign in to access the studio dashboard.');const allowed=(env.ADMIN_EMAILS||'').toLowerCase().split(',').map(s=>s.trim());if(!allowed.includes(email))fail(403,'This account does not have studio admin access.');return email;}
function sameOrigin(request){if(request.headers.get('Sec-Fetch-Site')==='cross-site')fail(403,'Please submit this request from the booking website.');const origin=request.headers.get('Origin');if(origin&&origin!==new URL(request.url).origin)fail(403,'Please submit this request from the booking website.');}
async function customer(request,env,id){const row=await first(env,'SELECT * FROM bookings WHERE id = ?',id);if(!row)fail(404,'This booking could not be found.');const token=request.headers.get('Authorization')?.replace(/^Bearer /,'');if(!token||await hash(token)!==row.token_hash)fail(403,'Use your private booking link to access this booking.');return row;}
function validRange(date,env){return /^\d{4}-\d{2}-\d{2}$/.test(date)&&date>=env.BOOKING_START_DATE&&date<=env.BOOKING_END_DATE;}
function active(row,timestamp){return row.status!=='cancelled'&&(row.status!=='pending_payment'||row.hold_expires_at>timestamp);}
async function availability(env,date,service){const slots=slotsForDate(date,service);const rows=await all(env,"SELECT start_at,end_at,status,hold_expires_at FROM bookings WHERE start_at < ? AND end_at > ? AND status != 'cancelled'",date+'T23:59:59.999Z',date+'T00:00:00.000Z');const stamp=now();return slots.filter(s=>!rows.some(r=>active(r,stamp)&&r.start_at<s.end&&r.end_at>s.start));}
async function createBooking(request,env){sameOrigin(request);const b=await body(request);const service=SERVICES.find(s=>s.id===b.serviceId);if(!service)fail(400,'Choose a session.');if(!validRange(b.date,env))fail(400,'Choose a date within the summer special.');const slot=slotsForDate(b.date,service).find(s=>s.time===b.time);if(!slot)fail(400,'Choose an available appointment time.');const name=text(b.name,'name');const email=text(b.email,'email address',254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'Enter a valid email address.');const phone=text(b.phone,'phone number',30);if(phone.replace(/\D/g,'').length<9)fail(400,'Enter a valid phone number.');const placement=text(b.placement,'placement');const idea=text(b.idea,'tattoo idea',2000);if(b.consent!==true)fail(400,'Please accept the booking and demo-payment terms.');if(!/^[\da-f-]{36}$/i.test(b.idempotencyKey||'')||!/^[\da-f]{64}$/i.test(b.accessToken||''))fail(400,'Please refresh the page and try again.');const tokenHash=await hash(b.accessToken);const existing=await first(env,'SELECT * FROM bookings WHERE idempotency_key = ?',b.idempotencyKey);if(existing){if(existing.token_hash!==tokenHash)fail(409,'Please start a new booking.');return json({booking:publicBooking(existing),bank:BANK},200);}
 const recent=await first(env,"SELECT count(*) AS total FROM bookings WHERE email = ? AND created_at > ?",email,new Date(Date.now()-3600000).toISOString());if(recent.total>=5)fail(429,'You have made several booking requests. Please contact the studio for help.');const id=uuid(),stamp=now(),reference='SAH-'+crypto.randomUUID().replaceAll('-','').slice(0,10).toUpperCase(),expires=new Date(Date.now()+3600000).toISOString();
 const inserted=await prepare(env,`INSERT INTO bookings (id,reference,token_hash,idempotency_key,name,email,phone,service_id,service_name,start_at,end_at,price,deposit,placement,idea,status,payment_status,hold_expires_at,created_at,updated_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'pending_payment','unpaid',?,?,? WHERE NOT EXISTS (SELECT 1 FROM bookings WHERE start_at < ? AND end_at > ? AND status != 'cancelled' AND (status != 'pending_payment' OR hold_expires_at > ?))`,id,reference,tokenHash,b.idempotencyKey,name,email,phone,service.id,service.name+' · '+service.description,slot.start,slot.end,service.price,Math.ceil(service.price/2),placement,idea,expires,stamp,stamp,slot.end,slot.start,stamp).run();if(!inserted.meta.changes)fail(409,'That time was just booked. Please choose another time.');await prepare(env,'INSERT INTO activity (id,booking_id,action,actor,created_at) VALUES (?,?,?,?,?)',uuid(),id,'Booking created','Customer',stamp).run();return json({booking:publicBooking(await first(env,'SELECT * FROM bookings WHERE id = ?',id)),bank:BANK},201);
}
async function uploadProof(request,env,id){sameOrigin(request);const row=await customer(request,env,id);if(['cancelled','completed'].includes(row.status)||row.status==='pending_payment'&&row.hold_expires_at<now())fail(409,'This booking is no longer awaiting payment. Please contact the studio or book again.');if(row.paid_amount>=row.price)fail(409,'This booking is already fully paid.');if(Number(request.headers.get('content-length'))>11*1024*1024)fail(413,'Choose a file smaller than 10 MB.');let form;try{form=await request.formData()}catch{fail(400,'The file could not be uploaded. Please try again.');}const file=form.get('proof');if(!file||typeof file==='string'||!file.size)fail(400,'Choose your proof of payment.');if(file.size>10*1024*1024)fail(413,'Choose a file smaller than 10 MB.');const signature=new Uint8Array(await file.slice(0,8).arrayBuffer());let mime;if(signature[0]===0xff&&signature[1]===0xd8&&signature[2]===0xff)mime='image/jpeg';else if([137,80,78,71,13,10,26,10].every((b,i)=>signature[i]===b))mime='image/png';else if(new TextDecoder().decode(signature.slice(0,5))==='%PDF-')mime='application/pdf';else fail(400,'Use a JPG, PNG or PDF proof of payment.');const count=await first(env,'SELECT count(*) AS total FROM proofs WHERE booking_id = ?',id);if(count.total>=5)fail(400,'The upload limit for this booking has been reached. Please contact the studio.');if(!env.BUCKET)throw new Error('Proof storage is unavailable.');const proofId=uuid(),key=`proofs/${id}/${proofId}`,stamp=now(),filename=file.name.replace(/[^\w .()-]/g,'_').slice(0,150);await env.BUCKET.put(key,file.stream(),{httpMetadata:{contentType:mime}});
 try{const uploaded=await db(env).batch([prepare(env,"INSERT INTO proofs (id,booking_id,object_key,filename,mime,size,created_at) SELECT ?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM bookings WHERE id = ? AND status NOT IN ('cancelled','completed') AND (status != 'pending_payment' OR hold_expires_at > ?)) AND (SELECT count(*) FROM proofs WHERE booking_id = ?) < 5",proofId,id,key,filename,mime,file.size,stamp,id,stamp,id),prepare(env,"UPDATE bookings SET status = CASE WHEN status = 'confirmed' THEN status ELSE 'payment_review' END,payment_status = 'review',updated_at = ? WHERE id = ? AND EXISTS (SELECT 1 FROM proofs WHERE id = ?)",stamp,id,proofId),prepare(env,'INSERT INTO activity (id,booking_id,action,actor,created_at) SELECT ?,?,?,?,? WHERE EXISTS (SELECT 1 FROM proofs WHERE id = ?)',uuid(),id,'Proof of payment uploaded','Customer',stamp,proofId)]);if(!uploaded[0].meta.changes)fail(409,'This booking is closed or its upload limit has been reached.');}catch(e){await env.BUCKET.delete(key);throw e;}
 return json({booking:publicBooking(await first(env,'SELECT * FROM bookings WHERE id = ?',id)),proof:{id:proofId,filename,status:'pending'}},201);
}
async function detail(env,id){const row=await first(env,'SELECT * FROM bookings WHERE id = ?',id);if(!row)fail(404,'Booking not found.');return{booking:{...publicBooking(row),notes:row.notes},proofs:await all(env,'SELECT id,filename,mime,size,status,created_at,reviewed_at,reviewer,reason FROM proofs WHERE booking_id = ? ORDER BY created_at DESC',id),payments:await all(env,'SELECT * FROM payments WHERE booking_id = ? ORDER BY created_at DESC',id),activity:await all(env,'SELECT * FROM activity WHERE booking_id = ? ORDER BY created_at DESC',id)};}
async function reviewProof(request,env,id,actor){sameOrigin(request);const b=await body(request);const proof=await first(env,'SELECT * FROM proofs WHERE id = ?',id);if(!proof)fail(404,'Proof not found.');if(proof.status!=='pending')fail(409,'This proof has already been reviewed.');const booking=await first(env,'SELECT * FROM bookings WHERE id = ?',proof.booking_id);if(['cancelled','completed'].includes(booking.status))fail(409,'This booking is closed.');const stamp=now();if(b.decision==='approve'){const amount=Number(b.amount);if(!Number.isInteger(amount)||amount<1||amount>booking.price-booking.paid_amount)fail(400,'Enter the verified payment amount, up to the outstanding balance.');const r=await db(env).batch([prepare(env,"INSERT INTO payments (id,booking_id,proof_id,amount,method,created_at,recorded_by,note) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM proofs WHERE id = ? AND status = 'pending') AND ? <= (SELECT price-paid_amount FROM bookings WHERE id = ?)",uuid(),booking.id,id,amount,'bank_transfer',stamp,actor,'Verified proof of payment',id,amount,booking.id),prepare(env,"UPDATE proofs SET status = 'approved',reviewed_at = ?,reviewer = ? WHERE id = ? AND EXISTS (SELECT 1 FROM payments WHERE proof_id = ?)",stamp,actor,id,id),prepare(env,"UPDATE bookings SET paid_amount = (SELECT coalesce(sum(amount),0) FROM payments WHERE booking_id = ?),status = CASE WHEN (SELECT coalesce(sum(amount),0) FROM payments WHERE booking_id = ?) >= deposit THEN 'confirmed' ELSE 'payment_review' END,payment_status = CASE WHEN (SELECT coalesce(sum(amount),0) FROM payments WHERE booking_id = ?) >= price THEN 'paid' WHEN (SELECT coalesce(sum(amount),0) FROM payments WHERE booking_id = ?) >= deposit THEN 'deposit_paid' ELSE 'partial' END,updated_at = ? WHERE id = ?",booking.id,booking.id,booking.id,booking.id,stamp,booking.id),prepare(env,'INSERT INTO activity (id,booking_id,action,actor,created_at) SELECT ?,?,?,?,? WHERE EXISTS (SELECT 1 FROM payments WHERE proof_id = ?)',uuid(),booking.id,`Payment verified: R${amount}`,actor,stamp,id)]);if(!r[0].meta.changes)fail(409,'This payment has already been processed or the outstanding balance changed.');}
 else if(b.decision==='reject'){const reason=text(b.reason,'reason for rejection',500);await db(env).batch([prepare(env,"UPDATE proofs SET status='rejected',reviewed_at=?,reviewer=?,reason=? WHERE id=? AND status='pending'",stamp,actor,reason,id),prepare(env,"UPDATE bookings SET status = CASE WHEN paid_amount >= deposit THEN 'confirmed' WHEN EXISTS (SELECT 1 FROM proofs WHERE booking_id = ? AND status = 'pending') THEN 'payment_review' ELSE 'pending_payment' END,payment_status = CASE WHEN paid_amount >= deposit THEN 'deposit_paid' WHEN EXISTS (SELECT 1 FROM proofs WHERE booking_id = ? AND status = 'pending') THEN 'review' ELSE 'rejected' END,hold_expires_at = ?,updated_at = ? WHERE id = ? AND status NOT IN ('cancelled','completed')",booking.id,booking.id,new Date(Date.now()+86400000).toISOString(),stamp,booking.id),prepare(env,'INSERT INTO activity (id,booking_id,action,actor,created_at) VALUES (?,?,?,?,?)',uuid(),booking.id,'Proof rejected: '+reason,actor,stamp)]);}
 else fail(400,'Choose approve or reject.');return json(await detail(env,booking.id));}
async function updateBooking(request,env,id,actor){sameOrigin(request);const b=await body(request);const booking=await first(env,'SELECT * FROM bookings WHERE id = ?',id);if(!booking)fail(404,'Booking not found.');if(b.action==='notes'){const notes=text(b.notes,'notes',4000,true);await prepare(env,'UPDATE bookings SET notes=?,updated_at=? WHERE id=?',notes,now(),id).run();return json(await detail(env,id));}
 if(b.action==='record_payment'){if(['cancelled','completed'].includes(booking.status)||(booking.status==='pending_payment'&&booking.hold_expires_at<now()))fail(409,'This booking is closed or expired.');const amount=Number(b.amount);if(!Number.isInteger(amount)||amount<=0||amount>booking.price-booking.paid_amount)fail(400,'Enter an amount up to the outstanding balance.');const note=text(b.note,'payment note',500);const stamp=now();const paymentId=uuid();const result=await db(env).batch([prepare(env,"INSERT INTO payments (id,booking_id,amount,method,created_at,recorded_by,note) SELECT ?,?,?,?,?,?,? WHERE ? <= (SELECT price-paid_amount FROM bookings WHERE id = ?)",paymentId,id,amount,'manual',stamp,actor,note,amount,id),prepare(env,"UPDATE bookings SET paid_amount=(SELECT coalesce(sum(amount),0) FROM payments WHERE booking_id=?),status=CASE WHEN (SELECT coalesce(sum(amount),0) FROM payments WHERE booking_id=?)>=deposit THEN 'confirmed' ELSE status END,payment_status=CASE WHEN (SELECT coalesce(sum(amount),0) FROM payments WHERE booking_id=?)>=price THEN 'paid' WHEN (SELECT coalesce(sum(amount),0) FROM payments WHERE booking_id=?)>=deposit THEN 'deposit_paid' ELSE 'partial' END,updated_at=? WHERE id=?",id,id,id,id,stamp,id),prepare(env,'INSERT INTO activity (id,booking_id,action,actor,created_at) SELECT ?,?,?,?,? WHERE EXISTS (SELECT 1 FROM payments WHERE id=?)',uuid(),id,`Payment recorded: R${amount} · ${note}`,actor,stamp,paymentId)]);if(!result[0].meta.changes)fail(409,'The outstanding balance changed. Refresh and try again.');return json(await detail(env,id));}
 if(!['cancelled','completed'].includes(b.action))fail(400,'Choose a valid booking action.');if(b.action==='completed'&&(booking.status!=='confirmed'||booking.paid_amount<booking.price))fail(400,'Confirm the appointment and record its full payment before marking it complete.');if(['cancelled','completed'].includes(booking.status))fail(409,'This booking is already closed.');await db(env).batch([prepare(env,'UPDATE bookings SET status=?,updated_at=? WHERE id=?',b.action,now(),id),prepare(env,'INSERT INTO activity (id,booking_id,action,actor,created_at) VALUES (?,?,?,?,?)',uuid(),id,b.action==='cancelled'?'Booking cancelled — any refund must be arranged separately':'Appointment completed',actor,now())]);return json(await detail(env,id));}
async function route(request,env){const u=new URL(request.url),path=u.pathname,method=request.method;
 if(path==='/api/config'&&method==='GET')return json({services:SERVICES,bank:BANK,schedule:SCHEDULE,startDate:env.BOOKING_START_DATE,endDate:env.BOOKING_END_DATE});
 if(path==='/api/availability'&&method==='GET'){const service=SERVICES.find(s=>s.id===u.searchParams.get('service'));const date=u.searchParams.get('date');if(!service||!validRange(date,env))fail(400,'Choose a valid session and date.');return json({slots:await availability(env,date,service)});}
 if(path==='/api/bookings'&&method==='POST')return createBooking(request,env);
 let m=path.match(/^\/api\/bookings\/([\da-f-]+)(\/proofs)?$/);if(m){if(m[2]&&method==='POST')return uploadProof(request,env,m[1]);if(!m[2]&&method==='GET'){const booking=await customer(request,env,m[1]);return json({booking:publicBooking(booking),bank:BANK,proofs:await all(env,'SELECT id,filename,status,created_at,reason FROM proofs WHERE booking_id = ? ORDER BY created_at DESC',booking.id)});}}
 if(path.startsWith('/api/admin/')){const actor=admin(request,env);if(path==='/api/admin/me')return json({email:actor});if(path==='/api/admin/bookings'&&method==='GET'){const rows=await all(env,'SELECT * FROM bookings ORDER BY start_at ASC LIMIT 1000');const proofCounts=await all(env,"SELECT booking_id,count(*) AS total,sum(CASE WHEN status='pending' THEN 1 ELSE 0 END) AS pending FROM proofs GROUP BY booking_id");return json({bookings:rows.map(r=>({...publicBooking(r),notes:r.notes,proofs:proofCounts.find(p=>p.booking_id===r.id)||{total:0,pending:0}}))});}
 m=path.match(/^\/api\/admin\/bookings\/([\da-f-]+)$/);if(m){if(method==='GET')return json(await detail(env,m[1]));if(method==='PATCH')return updateBooking(request,env,m[1],actor);}
 m=path.match(/^\/api\/admin\/proofs\/([\da-f-]+)(\/file)?$/);if(m){if(m[2]&&method==='GET'){const proof=await first(env,'SELECT * FROM proofs WHERE id = ?',m[1]);if(!proof)fail(404,'Proof not found.');const object=await env.BUCKET.get(proof.object_key);if(!object)fail(404,'The file could not be found.');return new Response(object.body,{headers:{'Content-Type':proof.mime,'Content-Disposition':`attachment; filename="${proof.filename.replaceAll('"','_')}"`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"}});}if(!m[2]&&method==='PATCH')return reviewProof(request,env,m[1],actor);}
 fail(404,'This action was not found.');}
 if(path.startsWith('/api/'))fail(404,'This action was not found.');
 if(path==='/admin'||path==='/admin/') {const asset=new URL(request.url);asset.pathname='/admin.html';return env.ASSETS.fetch(new Request(asset,request));}
 if(path==='/book'||path==='/book/'){const asset=new URL(request.url);asset.pathname='/book.html';return env.ASSETS.fetch(new Request(asset,request));}
 if(path==='/'){const asset=new URL(request.url);asset.pathname='/index.html';return env.ASSETS.fetch(new Request(asset,request));}
 return env.ASSETS.fetch(request);
}
export default{async fetch(request,env){try{const response=await route(request,env);const headers=new Headers(response.headers);headers.set('Referrer-Policy','no-referrer');headers.set('X-Content-Type-Options','nosniff');headers.set('Permissions-Policy','camera=(), microphone=(), geolocation=()');return new Response(response.body,{status:response.status,headers});}catch(error){if(!(error instanceof HttpError))console.error('Booking request failed',error.message);return json({error:error instanceof HttpError?error.message:'The studio service is temporarily unavailable. Your details are still on this page. Please try again.'},error.status||503);}}};
